<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDMBB2Dj\Glpi_Kernel_KernelProductionContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDMBB2Dj/Glpi_Kernel_KernelProductionContainer.php') {
    touch(__DIR__.'/ContainerDMBB2Dj.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionContainer::class, false)) {
    \class_alias(\ContainerDMBB2Dj\Glpi_Kernel_KernelProductionContainer::class, Glpi_Kernel_KernelProductionContainer::class, false);
}

return new \ContainerDMBB2Dj\Glpi_Kernel_KernelProductionContainer([
    'container.build_hash' => 'DMBB2Dj',
    'container.build_id' => 'f93cda85',
    'container.build_time' => 1778185866,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDMBB2Dj');
